import 'dart:math';
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import '../../core/models/app_models.dart';
import '../../core/models/app_settings.dart';
import '../../core/services/music_service.dart';
import '../../core/utils/helpers.dart';
import '../../core/i18n/app_strings.dart';

class StudyPage extends StatefulWidget {
  final Deck deck; final AppSettings settings; final List<FlashCard>? studyCards; final VoidCallback onChanged;
  const StudyPage({super.key,required this.deck,required this.settings,required this.onChanged,this.studyCards});
  @override State<StudyPage> createState()=>_StudyPageState();
}
class _StudyPageState extends State<StudyPage> with SingleTickerProviderStateMixin{
  late final List<FlashCard> queue; late final AnimationController flip; Timer? timer; int index=0,seconds=0; bool revealed=false,locked=false,musicOn=false; final music=MusicService.instance;
  String s(String k)=>AppStrings.t(context,k);
  @override void initState(){super.initState();queue=List<FlashCard>.from(widget.studyCards??widget.deck.cards.where((c)=>!c.dueAt.isAfter(DateTime.now())))..shuffle();flip=AnimationController(vsync:this,duration:Duration(milliseconds:widget.settings.animations?420:1));if(widget.settings.showTimer)timer=Timer.periodic(const Duration(seconds:1),(_){if(mounted)setState(()=>seconds++);});if(queue.isNotEmpty&&widget.settings.musicEnabled)_startMusic();}
  Future<void> _startMusic()async{try{await music.play(widget.settings.musicTrack,volume:widget.settings.musicVolume);if(mounted)setState(()=>musicOn=true);}catch(_){}}
  void _buzz(){if(widget.settings.haptics)HapticFeedback.selectionClick();}
  void _reveal(){if(locked||queue.isEmpty)return;setState(()=>revealed=!revealed);if(revealed)flip.forward();else flip.reverse();_buzz();}
  void _rate(int rating){if(locked||queue.isEmpty||!revealed)return;final c=queue[index];final last=max(0,widget.deck.boxes.length-1);final now=DateTime.now();c.reviews++;if(rating==0){c.lapses++;c.boxIndex=0;c.dueAt=now.add(const Duration(minutes:10));}else if(rating==1){c.boxIndex=c.boxIndex.clamp(0,last).toInt();c.dueAt=now.add(const Duration(days:1));}else if(rating==2){c.boxIndex=min(last,c.boxIndex+1);c.dueAt=now.add(Duration(days:[1,2,4,7,14,30][min(c.boxIndex,5)]));}else{c.boxIndex=min(last,c.boxIndex+2);c.dueAt=now.add(Duration(days:[2,4,7,14,30,60][min(c.boxIndex,5)]));}widget.onChanged();_buzz();if(index==queue.length-1){setState(()=>locked=true);_finish();return;}setState(()=>index++);revealed=false;flip.reset();if(widget.settings.autoReveal)Future.delayed(const Duration(milliseconds:260),(){if(mounted&&!locked)_reveal();});}
  void _swipe(DragEndDetails d){if(!revealed||locked)return;final v=d.primaryVelocity??0;if(v>500)_rate(2);else if(v< -500)_rate(1);}
  Future<void> _finish()async{await Future<void>.delayed(const Duration(milliseconds:180));if(!mounted)return;await showDialog<void>(context:context,builder:(_)=>AlertDialog(title:Text(s('done')),content:Text('${queue.length} ${s('cards_count')}\n${_fmt()}'),actions:[FilledButton(onPressed:()=>Navigator.pop(context),child:Text(s('great')))]));if(mounted)Navigator.pop(context);}
  String _fmt()=>'${(seconds~/60).toString().padLeft(2,'0')}:${(seconds%60).toString().padLeft(2,'0')}';
  @override void dispose(){timer?.cancel();flip.dispose();if(musicOn)music.stop();super.dispose();}
  @override Widget build(BuildContext context){if(queue.isEmpty)return Scaffold(appBar:AppBar(title:Text(s('study'))),body:Center(child:Padding(padding:const EdgeInsets.all(24),child:Text(s('no_due'),textAlign:TextAlign.center))));final c=queue[index];final p=((index+1)/queue.length).clamp(0.0,1.0).toDouble();return Scaffold(appBar:AppBar(title:Text('${index+1} / ${queue.length}'),actions:[if(widget.settings.showTimer)Padding(padding:const EdgeInsets.symmetric(horizontal:12),child:Center(child:Text(_fmt(),style:const TextStyle(fontWeight:FontWeight.w700)))),if(widget.settings.musicEnabled)IconButton(onPressed:()async{if(musicOn){await music.pause();if(mounted)setState(()=>musicOn=false);}else{await _startMusic();}},icon:Icon(musicOn?Icons.music_note:Icons.music_off),tooltip:s('music'))]),body:SafeArea(child:Padding(padding:const EdgeInsets.fromLTRB(14,10,14,16),child:Column(children:[if(widget.settings.showProgress)...[LinearProgressIndicator(value:p,minHeight:7),const SizedBox(height:12)],Expanded(child:GestureDetector(onTap:_reveal,onHorizontalDragEnd:_swipe,child:AnimatedBuilder(animation:flip,builder:(_,__) {final a=flip.value*pi;final front=a<=pi/2;final face=CardFace(text:front?c.front:c.back,image:front?c.frontImage:c.backImage,label:front?s('tap'):s('done'));return Transform(alignment:Alignment.center,transform:Matrix4.identity()..setEntry(3,2,.0012)..rotateY(a),child:front?face:Transform(alignment:Alignment.center,transform:Matrix4.rotationY(pi),child:face));}))),const SizedBox(height:10),if(revealed)Row(children:[Expanded(child:RateButton(s('again'),Icons.refresh_outlined,()=>_rate(0))),const SizedBox(width:6),Expanded(child:RateButton(s('hard'),Icons.trending_down_outlined,()=>_rate(1))),const SizedBox(width:6),Expanded(child:RateButton(s('good'),Icons.check_outlined,()=>_rate(2))),const SizedBox(width:6),Expanded(child:RateButton(s('easy'),Icons.bolt_outlined,()=>_rate(3)))])else Text(s('tap')),if(revealed)Padding(padding:const EdgeInsets.only(top:6),child:Text(s('swipe'),style:TextStyle(color:Theme.of(context).hintColor,fontSize:12))) ])));}
}
class CardFace extends StatelessWidget{final String text;final String? image;final String label;const CardFace({super.key,required this.text,required this.image,required this.label});@override Widget build(BuildContext context){return Card(elevation:3,child:Padding(padding:const EdgeInsets.all(20),child:Center(child:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.style_outlined,size:44),const SizedBox(height:14),SafeMemoryImage(base64:image,height:190,width:double.infinity,fit:BoxFit.contain,borderRadius:BorderRadius.circular(16),error:const SizedBox.shrink()),if(tryDecodeBase64Image(image)!=null)const SizedBox(height:12),if(text.trim().isNotEmpty)Text(text,textAlign:TextAlign.center,textDirection:Directionality.of(context),style:const TextStyle(fontSize:25,fontWeight:FontWeight.w800,height:1.35)),const SizedBox(height:18),Text(label,textAlign:TextAlign.center,style:TextStyle(color:Theme.of(context).hintColor))])))));}}
class RateButton extends StatelessWidget{final String text;final IconData icon;final VoidCallback onTap;const RateButton(this.text,this.icon,this.onTap);@override Widget build(BuildContext context)=>OutlinedButton(onPressed:onTap,child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(icon),Text(text,maxLines:1,overflow:TextOverflow.ellipsis)]));}
