import 'package:flutter/widgets.dart';
import '../models/app_settings.dart';

class AppStrings {
  static String t(BuildContext context, String key) {
    final settings = context.dependOnInheritedWidgetOfExactType<_LocaleScope>()?.settings;
    return _text(settings?.languageCode ?? 'fa', key);
  }

  static String forCode(String code, String key) => _text(code, key);

  static String _text(String code, String key) {
    final lang = code.split('-').first;
    final map = _translations[lang] ?? _translations['en']!;
    return map[key] ?? _translations['en']![key] ?? key;
  }

  static const Map<String, Map<String, String>> _translations = {
    'fa': {
      'settings':'تنظیمات','language':'زبان','ui_language':'زبان رابط کاربری','choose_language':'زبان مورد نظر را انتخاب کن.','appearance':'ظاهر و شیشه‌ای','theme':'تم رنگی','glass':'Glassmorphism','glass_sub':'شفافیت، حاشیه نورانی و عمق بیشتر','music':'موسیقی آرام‌بخش','music_study':'موسیقی هنگام مرور','experience':'تجربه و مرور هوشمند','daily_goal':'هدف روزانه','backup':'پشتیبان‌گیری','extra':'قابلیت‌های بیشتر','new_deck':'دسته جدید','cards':'کارت‌ها','today':'امروز','decks':'دسته‌های یادگیری','new_card':'کارت جدید','search':'جستجوی کارت...','study':'مرور','rename':'تغییر نام','delete':'حذف','save':'ذخیره','cancel':'لغو','boxes':'مدیریت خانه‌ها','all_cards':'همه کارت‌ها','due_cards':'کارت‌های آماده امروز','favorites':'فقط کارت‌های محبوب','no_cards':'کارت پیدا نشد','card_front':'روی کارت / سؤال','card_back':'پشت کارت / پاسخ','tags':'برچسب‌ها','box':'خانه','save_card':'ذخیره کارت','add_image':'افزودن عکس','change_image':'تغییر عکس','question':'سؤال • برای دیدن پاسخ ضربه بزن','answer':'پاسخ • برای برگشت ضربه بزن','again':'دوباره','hard':'سخت','good':'خوب','easy':'آسان','music_btn':'موسیقی','done':'جلسه تمام شد! 🎉','great':'عالیه','no_due':'در این حالت کارتی برای مرور نداری 🎉','swipe':'برای امتیازدهی، کارت را به چپ یا راست هم بکشید.','tap':'کارت را لمس کن تا پاسخ را ببینی.','goal_done':'هدف امروز کامل شد! 🎉','ready':'آماده‌ی یک مرور کوتاه؟','merge':'ادغام','replace':'جایگزینی','export':'خروجی گرفتن','import':'وارد کردن','backup_found':'دسته پیدا شد.'
    },
    'en': {
      'settings':'Settings','language':'Language','ui_language':'Interface language','choose_language':'Choose your preferred language.','appearance':'Appearance & Glass','theme':'Color theme','glass':'Glassmorphism','glass_sub':'Transparency, glowing borders and depth','music':'Relaxing music','music_study':'Music while studying','experience':'Study experience','daily_goal':'Daily goal','backup':'Backup','extra':'More features','new_deck':'New deck','cards':'Cards','today':'Today','decks':'Learning decks','new_card':'New card','search':'Search cards...','study':'Study','rename':'Rename','delete':'Delete','save':'Save','cancel':'Cancel','boxes':'Manage boxes','all_cards':'All cards','due_cards':'Due today','favorites':'Favorites only','no_cards':'No cards found','card_front':'Front / Question','card_back':'Back / Answer','tags':'Tags','box':'Box','save_card':'Save card','add_image':'Add image','change_image':'Change image','question':'Question • tap to reveal','answer':'Answer • tap to flip back','again':'Again','hard':'Hard','good':'Good','easy':'Easy','music_btn':'Music','done':'Session complete! 🎉','great':'Great!','no_due':'No cards to review in this mode 🎉','swipe':'Swipe left or right to rate the card.','tap':'Tap the card to reveal the answer.','goal_done':'Daily goal complete! 🎉','ready':'Ready for a quick review?','merge':'Merge','replace':'Replace','export':'Export','import':'Import','backup_found':'decks found.'
    },
    'de': {'settings':'Einstellungen','language':'Sprache','ui_language':'Oberflächensprache','choose_language':'Wähle deine bevorzugte Sprache.','appearance':'Darstellung & Glas','theme':'Farbthema','glass':'Glassmorphism','music':'Entspannungsmusik','music_study':'Musik beim Lernen','experience':'Lernerlebnis','daily_goal':'Tagesziel','backup':'Sicherung','extra':'Weitere Funktionen','new_deck':'Neues Deck','cards':'Karten','today':'Heute','decks':'Lerndecks','new_card':'Neue Karte','search':'Karten suchen...','study':'Lernen','rename':'Umbenennen','delete':'Löschen','save':'Speichern','cancel':'Abbrechen','boxes':'Boxen verwalten','all_cards':'Alle Karten','due_cards':'Heute fällig','favorites':'Nur Favoriten','no_cards':'Keine Karten gefunden','card_front':'Vorderseite / Frage','card_back':'Rückseite / Antwort','tags':'Tags','box':'Box','save_card':'Karte speichern','add_image':'Bild hinzufügen','change_image':'Bild ändern','question':'Frage • tippen zum Aufdecken','answer':'Antwort • tippen zum Zurückdrehen','again':'Nochmal','hard':'Schwer','good':'Gut','easy':'Einfach','music_btn':'Musik','done':'Sitzung abgeschlossen! 🎉','great':'Super!','no_due':'Keine Karten zur Wiederholung 🎉','swipe':'Zum Bewerten nach links oder rechts wischen.','tap':'Karte antippen, um die Antwort zu sehen.','goal_done':'Tagesziel erreicht! 🎉','ready':'Bereit für eine kurze Wiederholung?','merge':'Zusammenführen','replace':'Ersetzen','export':'Exportieren','import':'Importieren','backup_found':'Decks gefunden.'},
    'nl': {'settings':'Instellingen','language':'Taal','ui_language':'Taal van de interface','appearance':'Uiterlijk & glas','theme':'Kleurthema','glass':'Glassmorphism','music':'Ontspannende muziek','music_study':'Muziek tijdens studeren','experience':'Studie-ervaring','daily_goal':'Dagdoel','backup':'Back-up','extra':'Meer functies','new_deck':'Nieuw deck','cards':'Kaarten','today':'Vandaag','decks':'Leerdecks','new_card':'Nieuwe kaart','search':'Kaarten zoeken...','study':'Studeren','rename':'Hernoemen','delete':'Verwijderen','save':'Opslaan','cancel':'Annuleren','boxes':'Boxen beheren','all_cards':'Alle kaarten','due_cards':'Vandaag te doen','favorites':'Alleen favorieten','no_cards':'Geen kaarten gevonden','card_front':'Voorkant / Vraag','card_back':'Achterkant / Antwoord','tags':'Tags','box':'Box','save_card':'Kaart opslaan','add_image':'Afbeelding toevoegen','change_image':'Afbeelding wijzigen','question':'Vraag • tik om te onthullen','answer':'Antwoord • tik om terug te draaien','again':'Opnieuw','hard':'Moeilijk','good':'Goed','easy':'Makkelijk','done':'Sessie voltooid! 🎉','great':'Geweldig!','no_due':'Geen kaarten om te herhalen 🎉','swipe':'Veeg links of rechts om te beoordelen.','tap':'Tik op de kaart om het antwoord te zien.','goal_done':'Dagdoel voltooid! 🎉','ready':'Klaar voor een korte herhaling?','export':'Exporteren','import':'Importeren'},
    'es': {'settings':'Ajustes','language':'Idioma','ui_language':'Idioma de la interfaz','appearance':'Apariencia y cristal','theme':'Tema de color','glass':'Glassmorphism','music':'Música relajante','music_study':'Música al estudiar','experience':'Experiencia de estudio','daily_goal':'Objetivo diario','backup':'Copia de seguridad','extra':'Más funciones','new_deck':'Nuevo mazo','cards':'Tarjetas','today':'Hoy','decks':'Mazos de aprendizaje','new_card':'Nueva tarjeta','search':'Buscar tarjetas...','study':'Estudiar','rename':'Renombrar','delete':'Eliminar','save':'Guardar','cancel':'Cancelar','boxes':'Gestionar cajas','all_cards':'Todas las tarjetas','due_cards':'Pendientes de hoy','favorites':'Solo favoritas','no_cards':'No se encontraron tarjetas','card_front':'Frente / Pregunta','card_back':'Reverso / Respuesta','tags':'Etiquetas','box':'Caja','save_card':'Guardar tarjeta','add_image':'Añadir imagen','change_image':'Cambiar imagen','question':'Pregunta • toca para revelar','answer':'Respuesta • toca para volver','again':'Otra vez','hard':'Difícil','good':'Bien','easy':'Fácil','done':'¡Sesión completa! 🎉','great':'¡Genial!','no_due':'No hay tarjetas para repasar 🎉','swipe':'Desliza a izquierda o derecha para puntuar.','tap':'Toca la tarjeta para ver la respuesta.','goal_done':'¡Objetivo diario completado! 🎉','ready':'¿Listo para un repaso rápido?','export':'Exportar','import':'Importar'},
    'pt': {'settings':'Definições','language':'Idioma','ui_language':'Idioma da interface','appearance':'Aparência e vidro','theme':'Tema de cores','glass':'Glassmorphism','music':'Música relaxante','music_study':'Música durante o estudo','experience':'Experiência de estudo','daily_goal':'Meta diária','backup':'Backup','extra':'Mais recursos','new_deck':'Novo baralho','cards':'Cartões','today':'Hoje','decks':'Baralhos de estudo','new_card':'Novo cartão','search':'Pesquisar cartões...','study':'Estudar','rename':'Renomear','delete':'Eliminar','save':'Guardar','cancel':'Cancelar','boxes':'Gerir caixas','all_cards':'Todos os cartões','due_cards':'Para hoje','favorites':'Apenas favoritos','no_cards':'Nenhum cartão encontrado','card_front':'Frente / Pergunta','card_back':'Verso / Resposta','tags':'Etiquetas','box':'Caixa','save_card':'Guardar cartão','add_image':'Adicionar imagem','change_image':'Alterar imagem','question':'Pergunta • toque para revelar','answer':'Resposta • toque para voltar','again':'Novamente','hard':'Difícil','good':'Bom','easy':'Fácil','done':'Sessão concluída! 🎉','great':'Ótimo!','no_due':'Não há cartões para rever 🎉','swipe':'Deslize para a esquerda ou direita para avaliar.','tap':'Toque no cartão para ver a resposta.','goal_done':'Meta diária concluída! 🎉','ready':'Pronto para uma revisão rápida?','export':'Exportar','import':'Importar'},
    'fr': {'settings':'Réglages','language':'Langue','ui_language':'Langue de l’interface','appearance':'Apparence et verre','theme':'Thème de couleur','glass':'Glassmorphism','music':'Musique relaxante','music_study':'Musique pendant l’étude','experience':'Expérience d’étude','daily_goal':'Objectif quotidien','backup':'Sauvegarde','extra':'Plus de fonctions','new_deck':'Nouveau paquet','cards':'Cartes','today':'Aujourd’hui','decks':'Paquets d’apprentissage','new_card':'Nouvelle carte','search':'Rechercher des cartes...','study':'Réviser','rename':'Renommer','delete':'Supprimer','save':'Enregistrer','cancel':'Annuler','boxes':'Gérer les cases','all_cards':'Toutes les cartes','due_cards':'À réviser aujourd’hui','favorites':'Favoris uniquement','no_cards':'Aucune carte trouvée','card_front':'Recto / Question','card_back':'Verso / Réponse','tags':'Étiquettes','box':'Case','save_card':'Enregistrer la carte','add_image':'Ajouter une image','change_image':'Changer l’image','question':'Question • toucher pour révéler','answer':'Réponse • toucher pour retourner','again':'Encore','hard':'Difficile','good':'Bien','easy':'Facile','done':'Session terminée ! 🎉','great':'Super !','no_due':'Aucune carte à réviser 🎉','swipe':'Glissez à gauche ou à droite pour noter.','tap':'Touchez la carte pour voir la réponse.','goal_done':'Objectif quotidien atteint ! 🎉','ready':'Prêt pour une courte révision ?','export':'Exporter','import':'Importer'},
    'da': {'settings':'Indstillinger','language':'Sprog','ui_language':'Grænsefladesprog','appearance':'Udseende og glas','theme':'Farvetema','glass':'Glassmorphism','music':'Afslappende musik','music_study':'Musik under læring','experience':'Læringsoplevelse','daily_goal':'Dagligt mål','backup':'Sikkerhedskopi','extra':'Flere funktioner','new_deck':'Nyt sæt','cards':'Kort','today':'I dag','decks':'Læringssæt','new_card':'Nyt kort','search':'Søg efter kort...','study':'Lær','rename':'Omdøb','delete':'Slet','save':'Gem','cancel':'Annuller','boxes':'Administrer bokse','all_cards':'Alle kort','due_cards':'Til gennemgang i dag','favorites':'Kun favoritter','no_cards':'Ingen kort fundet','card_front':'Forside / Spørgsmål','card_back':'Bagside / Svar','tags':'Tags','box':'Boks','save_card':'Gem kort','add_image':'Tilføj billede','change_image':'Skift billede','question':'Spørgsmål • tryk for at afsløre','answer':'Svar • tryk for at vende tilbage','again':'Igen','hard':'Svær','good':'God','easy':'Let','done':'Session færdig! 🎉','great':'Flot!','no_due':'Ingen kort at gennemgå 🎉','swipe':'Stryg til venstre eller højre for at bedømme.','tap':'Tryk på kortet for at se svaret.','goal_done':'Dagens mål er nået! 🎉','ready':'Klar til en hurtig gennemgang?','export':'Eksporter','import':'Importer'},
    'fi': {'settings':'Asetukset','language':'Kieli','ui_language':'Käyttöliittymän kieli','appearance':'Ulkoasu ja lasi','theme':'Väriteema','glass':'Glassmorphism','music':'Rentouttava musiikki','music_study':'Musiikki opiskelun aikana','experience':'Opiskelukokemus','daily_goal':'Päivätavoite','backup':'Varmuuskopio','extra':'Lisää ominaisuuksia','new_deck':'Uusi pakka','cards':'Kortit','today':'Tänään','decks':'Opiskelupakat','new_card':'Uusi kortti','search':'Hae kortteja...','study':'Opiskele','rename':'Nimeä uudelleen','delete':'Poista','save':'Tallenna','cancel':'Peruuta','boxes':'Hallitse laatikoita','all_cards':'Kaikki kortit','due_cards':'Tänään kerrattavat','favorites':'Vain suosikit','no_cards':'Kortteja ei löytynyt','card_front':'Etupuoli / Kysymys','card_back':'Takapuoli / Vastaus','tags':'Tunnisteet','box':'Laatikko','save_card':'Tallenna kortti','add_image':'Lisää kuva','change_image':'Vaihda kuva','question':'Kysymys • napauta paljastaaksesi','answer':'Vastaus • napauta kääntääksesi','again':'Uudelleen','hard':'Vaikea','good':'Hyvä','easy':'Helppo','done':'Harjoitus valmis! 🎉','great':'Hienoa!','no_due':'Ei kerrattavia kortteja 🎉','swipe':'Pyyhkäise vasemmalle tai oikealle arvioidaksesi.','tap':'Napauta korttia nähdäksesi vastauksen.','goal_done':'Päivätavoite saavutettu! 🎉','ready':'Valmis nopeaan kertaukseen?','export':'Vie','import':'Tuo'},
    'no': {'settings':'Innstillinger','language':'Språk','ui_language':'Grensesnittspråk','appearance':'Utseende og glass','theme':'Fargetema','glass':'Glassmorphism','music':'Avslappende musikk','music_study':'Musikk under læring','experience':'Læringsopplevelse','daily_goal':'Daglig mål','backup':'Sikkerhetskopi','extra':'Flere funksjoner','new_deck':'Ny kortstokk','cards':'Kort','today':'I dag','decks':'Læringsstokker','new_card':'Nytt kort','search':'Søk etter kort...','study':'Studer','rename':'Gi nytt navn','delete':'Slett','save':'Lagre','cancel':'Avbryt','boxes':'Administrer bokser','all_cards':'Alle kort','due_cards':'For gjennomgang i dag','favorites':'Bare favoritter','no_cards':'Ingen kort funnet','card_front':'Forside / Spørsmål','card_back':'Bakside / Svar','tags':'Tagger','box':'Boks','save_card':'Lagre kort','add_image':'Legg til bilde','change_image':'Bytt bilde','question':'Spørsmål • trykk for å vise','answer':'Svar • trykk for å snu tilbake','again':'Igjen','hard':'Vanskelig','good':'Bra','easy':'Lett','done':'Økten er ferdig! 🎉','great':'Flott!','no_due':'Ingen kort å repetere 🎉','swipe':'Sveip venstre eller høyre for å vurdere.','tap':'Trykk på kortet for å se svaret.','goal_done':'Dagens mål er nådd! 🎉','ready':'Klar for en rask repetisjon?','export':'Eksporter','import':'Importer'},
    'ja': {'settings':'設定','language':'言語','ui_language':'インターフェース言語','appearance':'外観とガラス','theme':'カラーテーマ','glass':'Glassmorphism','music':'リラックス音楽','music_study':'学習中の音楽','experience':'学習体験','daily_goal':'1日の目標','backup':'バックアップ','extra':'その他の機能','new_deck':'新しいデッキ','cards':'カード','today':'今日','decks':'学習デッキ','new_card':'新しいカード','search':'カードを検索...','study':'学習','rename':'名前を変更','delete':'削除','save':'保存','cancel':'キャンセル','boxes':'ボックス管理','all_cards':'すべてのカード','due_cards':'今日の復習','favorites':'お気に入りのみ','no_cards':'カードがありません','card_front':'表 / 質問','card_back':'裏 / 答え','tags':'タグ','box':'ボックス','save_card':'カードを保存','add_image':'画像を追加','change_image':'画像を変更','question':'質問 • タップして答えを表示','answer':'答え • タップして戻る','again':'もう一度','hard':'難しい','good':'良い','easy':'簡単','done':'セッション完了！ 🎉','great':'すばらしい！','no_due':'復習するカードはありません 🎉','swipe':'左右にスワイプして評価します。','tap':'カードをタップして答えを表示します。','goal_done':'今日の目標達成！ 🎉','ready':'短い復習を始めますか？','export':'エクスポート','import':'インポート'},
    'ar': {'settings':'الإعدادات','language':'اللغة','ui_language':'لغة الواجهة','appearance':'المظهر والزجاج','theme':'السمة اللونية','glass':'Glassmorphism','music':'موسيقى هادئة','music_study':'الموسيقى أثناء الدراسة','experience':'تجربة الدراسة','daily_goal':'الهدف اليومي','backup':'نسخة احتياطية','extra':'مزايا إضافية','new_deck':'مجموعة جديدة','cards':'البطاقات','today':'اليوم','decks':'مجموعات التعلم','new_card':'بطاقة جديدة','search':'البحث عن البطاقات...','study':'مراجعة','rename':'إعادة تسمية','delete':'حذف','save':'حفظ','cancel':'إلغاء','boxes':'إدارة الصناديق','all_cards':'كل البطاقات','due_cards':'بطاقات اليوم','favorites':'المفضلة فقط','no_cards':'لا توجد بطاقات','card_front':'الوجه / السؤال','card_back':'الخلف / الإجابة','tags':'الوسوم','box':'الصندوق','save_card':'حفظ البطاقة','add_image':'إضافة صورة','change_image':'تغيير الصورة','question':'سؤال • اضغط لإظهار الإجابة','answer':'إجابة • اضغط للعودة','again':'مرة أخرى','hard':'صعب','good':'جيد','easy':'سهل','done':'انتهت الجلسة! 🎉','great':'رائع!','no_due':'لا توجد بطاقات للمراجعة 🎉','swipe':'اسحب يميناً أو يساراً للتقييم.','tap':'اضغط على البطاقة لرؤية الإجابة.','goal_done':'اكتمل الهدف اليومي! 🎉','ready':'هل أنت مستعد لمراجعة سريعة؟','export':'تصدير','import':'استيراد'},
    'he': {'settings':'הגדרות','language':'שפה','ui_language':'שפת הממשק','appearance':'מראה וזכוכית','theme':'ערכת צבעים','glass':'Glassmorphism','music':'מוזיקה מרגיעה','music_study':'מוזיקה בזמן הלמידה','experience':'חוויית למידה','daily_goal':'יעד יומי','backup':'גיבוי','extra':'תכונות נוספות','new_deck':'חפיסה חדשה','cards':'כרטיסים','today':'היום','decks':'חפיסות לימוד','new_card':'כרטיס חדש','search':'חיפוש כרטיסים...','study':'לימוד','rename':'שינוי שם','delete':'מחיקה','save':'שמירה','cancel':'ביטול','boxes':'ניהול תיבות','all_cards':'כל הכרטיסים','due_cards':'לסקירה היום','favorites':'מועדפים בלבד','no_cards':'לא נמצאו כרטיסים','card_front':'קדמי / שאלה','card_back':'אחורי / תשובה','tags':'תגיות','box':'תיבה','save_card':'שמירת כרטיס','add_image':'הוספת תמונה','change_image':'שינוי תמונה','question':'שאלה • הקש להצגה','answer':'תשובה • הקש לחזרה','again':'שוב','hard':'קשה','good':'טוב','easy':'קל','done':'הסשן הסתיים! 🎉','great':'מעולה!','no_due':'אין כרטיסים לסקירה 🎉','swipe':'החלק ימינה או שמאלה כדי לדרג.','tap':'הקש על הכרטיס כדי לראות את התשובה.','goal_done':'היעד היומי הושלם! 🎉','ready':'מוכן לחזרה קצרה?','export':'ייצוא','import':'ייבוא'},
  };
}

class LocaleScope extends InheritedWidget {
  final AppSettings settings;
  const LocaleScope({super.key, required this.settings, required super.child});
  @override bool updateShouldNotify(LocaleScope oldWidget) => oldWidget.settings != settings || oldWidget.settings.languageCode != settings.languageCode;
}
