import 'package:flutter/material.dart';
import '../../core/models/app_settings.dart';
import '../../core/services/music_service.dart';
import '../../core/theme/app_theme.dart';
import '../../core/i18n/app_strings.dart';
import '../../shared/widgets/animated_glass_card.dart';

class SettingsPage extends StatefulWidget {
  final AppSettings settings; final Future<void> Function() onImport; final Future<void> Function() onExport;
  const SettingsPage({super.key, required this.settings, required this.onImport, required this.onExport});
  @override State<SettingsPage> createState()=>_SettingsPageState();
}
class _SettingsPageState extends State<SettingsPage> {
  final music=MusicService.instance; bool preview=false; String search='';
  String s(String k)=>AppStrings.t(context,k);
  @override void dispose(){ if(preview)music.stop(); super.dispose(); }
  Future<void> _languagePicker() async {
    final c=TextEditingController();
    final selected=await showDialog<String>(context:context,builder:(dialog)=>StatefulBuilder(builder:(dialog,setDialog){
      final list=AppSettings.languages.where((l)=>'${l.nativeName} ${l.name}'.toLowerCase().contains(c.text.trim().toLowerCase())).toList();
      return AlertDialog(title:Text(s('language')), content: SizedBox(width:double.maxFinite,height:500,child:Column(children:[TextField(controller:c,onChanged:(_)=>setDialog((){}),prefixIcon:const Icon(Icons.search),decoration:InputDecoration(hintText:s('search'))),const SizedBox(height:8),Expanded(child:ListView.builder(itemCount:list.length,itemBuilder:(_,i){final l=list[i];final active=l.code==widget.settings.languageCode;return ListTile(leading:CircleAvatar(child:Text(l.code.split('-').first.toUpperCase())),title:Text(l.nativeName,style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:Text(l.name),trailing:active?Icon(Icons.check_circle,color:Theme.of(dialog).colorScheme.primary):null,onTap:()=>Navigator.pop(dialog,l.code));}))]))), actions:[TextButton(onPressed:()=>Navigator.pop(dialog),child:Text(s('cancel')))]);
    }));
    c.dispose(); if(selected!=null) await widget.settings.setLanguage(selected);
  }
  @override Widget build(BuildContext context)=>AnimatedBuilder(animation:widget.settings,builder:(context,_){return Scaffold(appBar:AppBar(title:Text(s('settings'),style:const TextStyle(fontWeight:FontWeight.w800))),body:ListView(padding:const EdgeInsets.fromLTRB(16,10,16,32),children:[
    AnimatedGlassCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[_heading(Icons.language_outlined,s('language')),const SizedBox(height:5),ListTile(contentPadding:EdgeInsets.zero,onTap:_languagePicker,leading:const Icon(Icons.translate_outlined),title:Text(s('ui_language'),style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text(AppStrings.names[widget.settings.languageCode]??widget.settings.languageCode),trailing:const Icon(Icons.chevron_right))])),
    const SizedBox(height:12),
    AnimatedGlassCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[_heading(Icons.palette_outlined,s('appearance')),const SizedBox(height:10),Text(s('theme'),style:const TextStyle(fontWeight:FontWeight.w800)),const SizedBox(height:10),SizedBox(height:92,child:ListView.separated(scrollDirection:Axis.horizontal,itemCount:AppTheme.themes.length,separatorBuilder:(_,__)=>const SizedBox(width:9),itemBuilder:(_,i){final t=AppTheme.themes[i];final active=i==widget.settings.themeIndex;return InkWell(borderRadius:BorderRadius.circular(18),onTap:()=>widget.settings.setTheme(i),child:AnimatedContainer(duration:const Duration(milliseconds:180),width:116,padding:const EdgeInsets.all(8),decoration:BoxDecoration(gradient:LinearGradient(colors:[t.primary,t.secondary]),borderRadius:BorderRadius.circular(18),border:Border.all(color:active?Colors.white:Colors.white24,width:active?3:1),boxShadow:[BoxShadow(color:t.primary.withValues(alpha:.16),blurRadius:12)]),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(active?Icons.check_circle:Icons.palette_outlined,color:Colors.white),const SizedBox(height:4),Text('${i+1}. ${t.name}',maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w700,fontSize:11))])));})),const SizedBox(height:6),SwitchListTile(contentPadding:EdgeInsets.zero,title:Text(s('glass')),subtitle:Text(s('glass_sub')),value:widget.settings.glass,onChanged:(v)=>widget.settings.setBool('glass',v)),if(widget.settings.glass)Row(children:[Expanded(child:Slider(value:widget.settings.glassOpacity,min:.4,max:.9,divisions:10,onChanged:widget.settings.setGlassOpacity)),Text('${(widget.settings.glassOpacity*100).round()}%')])])),
    const SizedBox(height:12),
    AnimatedGlassCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[_heading(Icons.music_note_outlined,s('music')),SwitchListTile(contentPadding:EdgeInsets.zero,title:Text(s('music_study')),value:widget.settings.musicEnabled,onChanged:(v)async{await widget.settings.setBool('music_enabled',v);if(!v){await music.stop();if(mounted)setState(()=>preview=false);}}),if(widget.settings.musicEnabled)...[DropdownButtonFormField<String>(value:widget.settings.musicTrack,isExpanded:true,decoration:InputDecoration(labelText:s('music')),items:[for(final t in MusicService.tracks)DropdownMenuItem(value:t.id,child:Text(t.title))],onChanged:(v)async{if(v!=null){await widget.settings.setMusicTrack(v);if(preview)await music.play(v,volume:widget.settings.musicVolume);}}),Row(children:[const Icon(Icons.volume_down_outlined),Expanded(child:Slider(value:widget.settings.musicVolume,min:.05,max:.8,divisions:15,onChanged:(v)async{await widget.settings.setMusicVolume(v);if(preview)await music.setVolume(v);})),const Icon(Icons.volume_up_outlined)]),OutlinedButton.icon(onPressed:()async{if(preview)await music.pause();else await music.play(widget.settings.musicTrack,volume:widget.settings.musicVolume);if(mounted)setState(()=>preview=!preview);},icon:Icon(preview?Icons.pause:Icons.play_arrow),label:Text(s('music_btn')))] ])),
    const SizedBox(height:12),
    AnimatedGlassCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[_heading(Icons.tune_outlined,s('experience')), _switch('animations',Icons.auto_awesome_outlined,widget.settings.animations),_switch('haptics',Icons.vibration_outlined,widget.settings.haptics),_switch('auto_reveal',Icons.flip_outlined,widget.settings.autoReveal),_switch('progress',Icons.linear_scale_outlined,widget.settings.showProgress),_switch('timer',Icons.timer_outlined,widget.settings.showTimer),ListTile(contentPadding:EdgeInsets.zero,title:Text(s('daily_goal')),trailing:Text('${widget.settings.dailyGoal}'),subtitle:Slider(value:widget.settings.dailyGoal.toDouble(),min:5,max:100,divisions:19,onChanged:(v)=>widget.settings.setDailyGoal(v.round()))) ])),
    const SizedBox(height:12),
    AnimatedGlassCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[_heading(Icons.backup_outlined,s('backup')),Row(children:[Expanded(child:OutlinedButton.icon(onPressed:widget.onExport,icon:const Icon(Icons.upload_file_outlined),label:Text(s('export')))),const SizedBox(width:10),Expanded(child:OutlinedButton.icon(onPressed:widget.onImport,icon:const Icon(Icons.download_outlined),label:Text(s('import'))))])]))
  ]);});
  Widget _heading(IconData i,String t)=>Row(children:[Icon(i,color:Theme.of(context).colorScheme.primary),const SizedBox(width:8),Expanded(child:Text(t,style:const TextStyle(fontSize:17,fontWeight:FontWeight.w900)))]);
  Widget _switch(String key,IconData icon,bool value)=>SwitchListTile(contentPadding:EdgeInsets.zero,secondary:Icon(icon),title:Text(key=='animations'?s('animations'):key=='haptics'?s('haptics'):key=='auto_reveal'?s('auto_reveal'):key=='progress'?s('progress'):s('timer')),value:value,onChanged:(v)=>widget.settings.setBool(key,v));
}
